environment:
  orgIdentifier: TestDataSourceRemoteEnvironment_h_nbW1
  projectIdentifier: TestDataSourceRemoteEnvironment_h_nbW1
  identifier: TestDataSourceRemoteEnvironment_h_nbW1
  tags: {}
  name: TestDataSourceRemoteEnvironment_h_nbW1
  type: PreProduction
