environment:
  orgIdentifier: TestDataSourceRemoteEnvironment_y3a0YK
  projectIdentifier: TestDataSourceRemoteEnvironment_y3a0YK
  identifier: TestDataSourceRemoteEnvironment_y3a0YK
  tags: {}
  name: TestDataSourceRemoteEnvironment_y3a0YK
  type: PreProduction
