environment:
  orgIdentifier: TestDataSourceRemoteEnvironment_gUexH5
  projectIdentifier: TestDataSourceRemoteEnvironment_gUexH5
  identifier: TestDataSourceRemoteEnvironment_gUexH5
  tags: {}
  name: TestDataSourceRemoteEnvironment_gUexH5
  type: PreProduction
