environment:
  orgIdentifier: TestDataSourceRemoteEnvironment_W8plLq
  projectIdentifier: TestDataSourceRemoteEnvironment_W8plLq
  identifier: TestDataSourceRemoteEnvironment_W8plLq
  tags: {}
  name: TestDataSourceRemoteEnvironment_W8plLq
  type: PreProduction
