environment:
  orgIdentifier: TestDataSourceRemoteEnvironment_c_6aIU
  projectIdentifier: TestDataSourceRemoteEnvironment_c_6aIU
  identifier: TestDataSourceRemoteEnvironment_c_6aIU
  tags: {}
  name: TestDataSourceRemoteEnvironment_c_6aIU
  type: PreProduction
