environment:
  orgIdentifier: TestDataSourceRemoteEnvironment_YXbu3v
  projectIdentifier: TestDataSourceRemoteEnvironment_YXbu3v
  identifier: TestDataSourceRemoteEnvironment_YXbu3v
  tags: {}
  name: TestDataSourceRemoteEnvironment_YXbu3v
  type: PreProduction
