environment:
  orgIdentifier: TestDataSourceRemoteEnvironment_jIfl7_
  projectIdentifier: TestDataSourceRemoteEnvironment_jIfl7_
  identifier: TestDataSourceRemoteEnvironment_jIfl7_
  tags: {}
  name: TestDataSourceRemoteEnvironment_jIfl7_
  type: PreProduction
