environment:
  orgIdentifier: TestDataSourceRemoteEnvironment__JSZIl
  projectIdentifier: TestDataSourceRemoteEnvironment__JSZIl
  identifier: TestDataSourceRemoteEnvironment__JSZIl
  tags: {}
  name: TestDataSourceRemoteEnvironment__JSZIl
  type: PreProduction
