environment:
  orgIdentifier: TestDataSourceRemoteEnvironment_1AmVYc
  projectIdentifier: TestDataSourceRemoteEnvironment_1AmVYc
  identifier: TestDataSourceRemoteEnvironment_1AmVYc
  tags: {}
  name: TestDataSourceRemoteEnvironment_1AmVYc
  type: PreProduction
