environment:
  orgIdentifier: TestDataSourceRemoteEnvironment_iDHWqU
  projectIdentifier: TestDataSourceRemoteEnvironment_iDHWqU
  identifier: TestDataSourceRemoteEnvironment_iDHWqU
  tags: {}
  name: TestDataSourceRemoteEnvironment_iDHWqU
  type: PreProduction
