environment:
  orgIdentifier: TestDataSourceRemoteEnvironment_jIUkRT
  projectIdentifier: TestDataSourceRemoteEnvironment_jIUkRT
  identifier: TestDataSourceRemoteEnvironment_jIUkRT
  tags: {}
  name: TestDataSourceRemoteEnvironment_jIUkRT
  type: PreProduction
