environment:
  orgIdentifier: TestDataSourceRemoteEnvironment_akqJ28
  projectIdentifier: TestDataSourceRemoteEnvironment_akqJ28
  identifier: TestDataSourceRemoteEnvironment_akqJ28
  tags: {}
  name: TestDataSourceRemoteEnvironment_akqJ28
  type: PreProduction
