environment:
  orgIdentifier: TestDataSourceRemoteEnvironment_h8H8tu
  projectIdentifier: TestDataSourceRemoteEnvironment_h8H8tu
  identifier: TestDataSourceRemoteEnvironment_h8H8tu
  tags: {}
  name: TestDataSourceRemoteEnvironment_h8H8tu
  type: PreProduction
