environment:
  orgIdentifier: TestDataSourceRemoteEnvironment_7NWhOc
  projectIdentifier: TestDataSourceRemoteEnvironment_7NWhOc
  identifier: TestDataSourceRemoteEnvironment_7NWhOc
  tags: {}
  name: TestDataSourceRemoteEnvironment_7NWhOc
  type: PreProduction
