environment:
  orgIdentifier: TestDataSourceRemoteEnvironment_VShorP
  projectIdentifier: TestDataSourceRemoteEnvironment_VShorP
  identifier: TestDataSourceRemoteEnvironment_VShorP
  tags: {}
  name: TestDataSourceRemoteEnvironment_VShorP
  type: PreProduction
