environment:
  orgIdentifier: TestDataSourceRemoteEnvironment_u6IXQd
  projectIdentifier: TestDataSourceRemoteEnvironment_u6IXQd
  identifier: TestDataSourceRemoteEnvironment_u6IXQd
  tags: {}
  name: TestDataSourceRemoteEnvironment_u6IXQd
  type: PreProduction
